services:
  tyk-redis:
    image: redis:7.0-alpine3.16
    networks:
      - tyk
    ports:
      - "127.0.0.1:6379:6379"
    environment:
      - REDIS_ARGS=--save 20 1
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - redis:/data
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.3.2
    networks:
      - tyk
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - TYK_GW_SECRET=76a76e2a-eff8-4e90-9195-c550f8038e3d
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
    depends_on:
      - tyk-redis

networks:
  tyk:

volumes:
  redis:
