services:
  app1:
    image: ghcr.io/xurvan/app1:latest
  app2:
    image: ghcr.io/xurvan/app2:latest
    networks:
      lan:
        ipv4_address: 172.16.0.11
    ports:
      - "127.0.0.1:8001:80"
  tyk-redis:
    image: redis:7.0-alpine3.16
    networks:
      lan:
        ipv4_address: 172.16.0.2
    environment:
      - REDIS_ARGS=--save 20 1
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - redis:/data
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.3.2
    networks:
      lan:
        ipv4_address: 172.16.0.10
    ports:
      - "127.0.0.1:8000:8080"
    environment:
      - TYK_GW_SECRET=76a76e2a-eff8-4e90-9195-c550f8038e3d
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
    depends_on:
      - tyk-redis

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
    driver_opts:
      com.docker.network.bridge.name: "br-monorepo"

volumes:
  redis:
