services:
  tyk-redis:
    image: redis:7.0-alpine3.16
    networks:
      lan:
        ipv4_address: 172.16.0.2
    environment:
      - REDIS_ARGS=--save 20 1
      - REDIS_APPENDONLY=yes
      - REDIS_APPENDFSYNC=always
    volumes:
      - redis:/data
  tyk-gateway:
    image: docker.tyk.io/tyk-gateway/tyk-gateway:v5.3.2
    networks:
      lan:
        ipv4_address: 172.16.0.10
    ports:
      - "127.0.0.1:8000:8080"
    environment:
      - TYK_GW_SECRET=76a76e2a-eff8-4e90-9195-c550f8038e3d
    volumes:
      - ./tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./tyk/apps:/opt/tyk-gateway/apps
    depends_on:
      - tyk-redis
  hello-world:
    image: ghcr.io/xurvan/hello-world:latest
  rest:
    image: ghcr.io/xurvan/rest:latest
    networks:
      lan:
        ipv4_address: 172.16.0.11
    ports:
      - "127.0.0.1:8001:8080"
  grpc:
    image: ghcr.io/xurvan/grpc:latest
    networks:
      lan:
        ipv4_address: 172.16.0.12
    ports:
      - "127.0.0.1:9001:9090"
  twirp:
    image: ghcr.io/xurvan/twirp:latest
    networks:
      lan:
        ipv4_address: 172.16.0.13
    ports:
      - "127.0.0.1:8002:8080"
  perfect-postgres:
    image: postgres:16.3-alpine3.20
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=perfect
    networks:
      lan:
        ipv4_address: 172.16.0.14
    volumes:
      - postgres:/var/lib/postgresql/data
  perfect:
    image: ghcr.io/xurvan/app5:latest
    environment:
      - DATABASE_URL=postgres://postgres:postgres@app5-postgres:5432/perfect?sslmode=disable
    networks:
      lan:
        ipv4_address: 172.16.0.15
    ports:
      - "127.0.0.1:8003:8080"

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16
    driver_opts:
      com.docker.network.bridge.name: "br-monorepo"

volumes:
  postgres:
  redis:
