tasks:
  fix:
    command: 'go fmt ./...'
  check:
    command: 'go vet ./...'
  test:
    command: 'go test ./...'
  build:
    env:
      CGO_ENABLED: '0'
      GOOS: 'linux'
      GOARCH: 'amd64'
    command: 'go build -ldflags="-s" -ldflags="-w" -gcflags="-N" -gcflags="-l" -o bin/app cmd/main.go'
    inputs:
      - 'cmd/main.go'
    outputs:
      - 'bin/app'
  docker:
    command: 'docker build -t ghcr.io/xurvan/$project:latest .'
    inputs:
      - 'Dockerfile'
      - 'bin/app'
    deps:
      - '~:build'
  publish:
    command: 'docker push ghcr.io/xurvan/$project:latest'
    inputs:
      - 'Dockerfile'
      - 'bin/app'
    deps:
      - '~:docker'
